mkdir "$1/$2"
file="$1/$2/README.txt"
echo "Instructions on the files and folder structure" >> "$file"
echo "HOW TO NAME FILES" >> "$file"
cat "$file"
mkdir "$1/$2/00_Paperwork"
mkdir "$1/$2/01_Input"
mkdir "$1/$2/01_Input/img"
mkdir "$1/$2/01_Input/video"
mkdir "$1/$2/01_Input/docs"
touch "$1/$2/01_Input/brief.txt"
mkdir "$1/$2/01_Input/audio"
file2="$1/$2/01_Input/stakeholders.txt"
echo "CLIENT" >> "$file2"
echo "Company:" >> "$file2"
echo "Name:" >> "$file2"
echo "Position:" >> "$file2"
echo "tel:" >> "$file2"
echo "mail:" >> "$file2"
echo " " >> "$file2"
echo "—————" >> "$file2"
echo " " >> "$file2"
echo "PROVIDER" >> "$file2"
echo "Company:" >> "$file2"
echo "Name:" >> "$file2"
echo "Position:" >> "$file2"
echo "tel:" >> "$file2"
echo "mail:" >> "$file2"
cat "$file2"
mkdir "$1/$2/02_Output"
mkdir "$1/$2/02_Output/Deliveries"
mkdir "$1/$2/02_Output/Deliveries/00Month"
mkdir "$1/$2/02_Output/Presentations"
mkdir "$1/$2/02_Output/Presentations/00Month"
mkdir "$1/$2/Moodboard"
mkdir "$1/$2/Files"
mkdir "$1/$2/Files/Ai"
mkdir "$1/$2/Files/Ae"
mkdir "$1/$2/Files/Ind"
mkdir "$1/$2/Files/Ps"
mkdir "$1/$2/Files/Fig"
mkdir "$1/$2/Files/Key"
mkdir "$1/$2/Assets"
mkdir "$1/$2/Assets/img"
mkdir "$1/$2/Assets/video"
mkdir "$1/$2/Assets/fonts"