mkdir "$1/$2"
mkdir "$1/$2/00_Paperwork"
mkdir "$1/$2/01_Input"
mkdir "$1/$2/01_Input/img"
mkdir "$1/$2/01_Input/video"
mkdir "$1/$2/01_Input/docs"
touch "$1/$2/01_Input/brief.txt"
mkdir "$1/$2/01_Input/audio"
file2="$1/$2/01_Input/stakeholders.txt"
echo "CLIENTS" >> "$file2"
echo "Company:" >> "$file2"
echo "Name:" >> "$file2"
echo "Position:" >> "$file2"
echo "tel:" >> "$file2"
echo "mail:" >> "$file2"
echo " " >> "$file2"
echo "—————" >> "$file2"
echo " " >> "$file2"
echo "PROVIDERS" >> "$file2"
echo "Company:" >> "$file2"
echo "Name:" >> "$file2"
echo "Position:" >> "$file2"
echo "tel:" >> "$file2"
echo "mail:" >> "$file2"
cat "$file2"
mkdir "$1/$2/02_Output"
mkdir "$1/$2/02_Output/Deliveries"
mkdir "$1/$2/02_Output/Deliveries/00Month"
mkdir "$1/$2/02_Output/Presentations"
mkdir "$1/$2/02_Output/Presentations/00Month"
mkdir "$1/$2/Moodboard"
mkdir "$1/$2/Files"
mkdir "$1/$2/Files/Ai"
mkdir "$1/$2/Files/Ae"
mkdir "$1/$2/Files/Ind"
mkdir "$1/$2/Files/Ps"
mkdir "$1/$2/Files/Fig"
mkdir "$1/$2/Files/Key"
mkdir "$1/$2/Assets"
mkdir "$1/$2/Assets/img"
mkdir "$1/$2/Assets/video"
mkdir "$1/$2/Assets/fonts"
file="$1/$2/README.txt"
echo "The combination of folder paths and naming ensures the optimal workflow. According to the project, the folder structure may be morphed to fulfill the project needs." >> "$file"
echo "–––" >> "$file"
echo "# Folder and  File Structure" >> "$file"
echo "The folder structure has been designed to standardize all projects, making it agile to share with other professionals and maintain a certain order. It also allows sharing specific folders with the client, maintaining the progress of the project private. Each folder is detailed below:" >> "$file"
echo "–––" >> "$file"
echo "## Folders" >> "$file"
echo "" >> "$file"
echo "### 00_Paperwork" >> "$file"
echo "This folder contains, as its name indicates, all the bureaucracy of the project." >> "$file"
echo "" >> "$file"
echo "### 01_Input" >> "$file"
echo "This folder must contain all the information and data provided by the client. All original files must be kept here." >> "$file"
echo "" >> "$file"
echo "### 02_Output" >> "$file"
echo "This folder contains Deliveries and Presentations, both organized by date. This folder is meant to be sent and shared with the client, providing them a clean and organized deliverables without the clutter of other technical files." >> "$file"
echo "" >> "$file"
echo "### Assets" >> "$file"
echo "This folder contains all assets organized by categories. By the fault a fonts, img and video folders are created." >> "$file"
echo "" >> "$file"
echo "### Files" >> "$file"
echo "This folder hosts all the files used to develop the project. Organized by apps." >> "$file"
echo "" >> "$file"
echo "### Moodboard" >> "$file"
echo "All images, videos, pdf, notes... must be located here. The naming of the files in this folder, has to be the original file name, for easy finding of the source." >> "$file"
echo "–––" >> "$file"
echo "## Files" >> "$file"
echo "" >> "$file"
echo "## README.txt" >> "$file"
echo "A text file that details new collaborators and team members to respect the structure and the importance of a tidy project. Instructs on folder structure and the standard to name files." >> "$file"
echo "" >> "$file"
echo "## brief.txt" >> "$file"
echo "The project brief by the client and its respective modifications." >> "$file"
echo "" >> "$file"
echo "## stakeholders.txt" >> "$file"
echo "This file contains all the contact information of clients and providers involved in the project." >> "$file"
echo "" >> "$file"
echo "# File Naming" >> "$file"
echo "Standardizing a nomenclature system, ensures a fast retrieval of documents and avoids breaking links." >> "$file"
echo "" >> "$file"
echo "## Hierarchy" >> "$file"
echo "### Version" >> "$file"
echo "To order folders and files, a two digit followed by an underscore must be placed 00_. Combined with the finder feature to order by name, we can ensure a list of items. Used to determinate priority or the latest version of the file." >> "$file"
echo "" >> "$file"
echo "### CAPS" >> "$file"
echo "Used for files or folders with a high priority, but are not part of the list. CALLS ATTENTION." >> "$file"
echo "" >> "$file"
echo "### lower case" >> "$file"
echo "Short and non-complex files, must be named in lower case. An example could be: brief.txt" >> "$file"
echo "" >> "$file"
echo "### TitleCase" >> "$file"
echo "For long and complex phrases. An example could be: 00_NameOfTheFile" >> "$file"
echo "" >> "$file"
echo "## Underscore" >> "$file"
echo "The underscore _ is used to separate data inputs in the file name. An example could be: 00_FileName." >> "$file"
echo "" >> "$file"
echo "## Dates" >> "$file"
echo "Use it for deliveries and exports. Can be combined with file version. The format is ddMM, using the month abbreviation for shorter file names. An example could be: 14June_." >> "$file"
echo "" >> "$file"
echo "| Month     | Abbreviation  |" >> "$file"
echo "|-----------|---------------|" >> "$file"
echo "| January   | Jan.          |" >> "$file"
echo "| February  | Feb.          |" >> "$file"
echo "| March     | Mar.          |" >> "$file"
echo "| April     | Apr.          |" >> "$file"
echo "| May       | May           |" >> "$file"
echo "| June      | Jun.          |" >> "$file"
echo "| July      | Jul.          |" >> "$file"
echo "| August    | Aug.          |" >> "$file"
echo "| September | Sep. or Sept. |" >> "$file"
echo "| October   | Oct.          |" >> "$file"
echo "| November  | Nov.          |" >> "$file"
echo "| December  | Dec.          |" >> "$file"
echo "–––" >> "$file"
echo "App by vicenteakira, learn more at https://github.com/vicenteakira/ProjectBentoFolders" >> "$file"
cat "$file"